name: donate_me_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  supabase_flutter: ^2.9.1
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.5.3
  go_router: ^16.0.0
  flutter_svg: ^2.2.0
  flutter_form_builder: ^10.1.0
  form_builder_validators: ^11.2.0
  provider: ^6.1.5
  image_picker: ^1.1.2
  file_picker: ^8.1.2
  http: ^1.2.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - .env
